<a href="https://colab.research.google.com/github/jaswanthbhavanam-03/SivaSaiJaswanthBhavanam_INFO5731_Spring2026/blob/main/In_Class_Exercise_Combined_ipynb_8_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In-Class Exercise: Sentiment Analysis + Text Classification + Prompt Engineering

**Course:** NLP / Text Mining  
**Total Points:** 30  
**Suggested Time:** about 45 minutes total  
**Dataset:** `sentiment_classification_combined_data.csv`

**Instructions**
- Complete all questions in this notebook.
- Run all cells before submission.
- Keep your answers clear and organized.
- For the prompt engineering part, you do **not** need an API key.

## Part A — Sentiment Analysis with VADER (10 points)
In this part, use **VADER** to compute sentiment scores for the text data.

In [1]:
# Upload the dataset file from your computer (Google Colab)
from google.colab import files

uploaded = files.upload()
filename = next(iter(uploaded))
print("Uploaded file name:", filename)

Saving sentiment_classification_combined_data.csv to sentiment_classification_combined_data.csv
Uploaded file name: sentiment_classification_combined_data.csv

### Q1. Load and inspect the dataset (2 points)
Show:
1. the first 5 rows  
2. the shape of the dataset  
3. the column names

In [3]:
# Read the uploaded CSV file
import pandas as pd

df = pd.read_csv(filename)

# First 5 rows
print("First 5 rows:")
print(df.head())

# Shape
print("\nShape of dataset:")
print(df.shape)

# Column names
print("\nColumn names:")
print(df.columns)

First 5 rows:
                                                Text TrueLabel  Score
0  I loved this healthcare AI workshop. The examp...  positive      5
1  This lecture was okay, but some parts were con...   neutral      3
2  The notebook was easy to follow and very pract...  positive      5
3  I did not like the explanation of the model re...  negative      1
4  The activity was interesting and helped me und...  positive      4

Shape of dataset:
(24, 3)

Column names:
Index(['Text', 'TrueLabel', 'Score'], dtype='object')

### Q2. Apply VADER to compute sentiment scores (3 points)
- Import VADER
- Download the lexicon if needed
- Create a new column called `compound`
- Show the first 5 rows of `Text` and `compound`

In [7]:
!pip -q install nltk
import nltk
nltk.download('vader_lexicon')
from nltk.sentiment import SentimentIntensityAnalyzer
sia = SentimentIntensityAnalyzer()

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [8]:
# Write your answer here
!pip -q install nltk

import nltk
nltk.download('vader_lexicon')

from nltk.sentiment import SentimentIntensityAnalyzer
sia = SentimentIntensityAnalyzer()

# Apply VADER to compute compound score
df['compound'] = df['Text'].apply(lambda x: sia.polarity_scores(str(x))['compound'])

# Show first 5 rows
df[['Text', 'compound']].head()

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

                                                Text  compound
0  I loved this healthcare AI workshop. The examp...    0.8555
1  This lecture was okay, but some parts were con...   -0.2263
2  The notebook was easy to follow and very pract...    0.4404
3  I did not like the explanation of the model re...   -0.2755
4  The activity was interesting and helped me und...    0.4019

### Q3. Create a sentiment label from the compound score (3 points)
Create a new column called `PredictedSentiment` using this rule:
- `compound >= 0.05` → `positive`
- `compound <= -0.05` → `negative`
- otherwise → `neutral`

Then show the first 10 rows of `Text`, `compound`, and `PredictedSentiment`.

In [5]:
# Write your answer here
# Function to assign sentiment label
def get_sentiment_label(score):
    if score >= 0.05:
        return "positive"
    elif score <= -0.05:
        return "negative"
    else:
        return "neutral"

# Apply function
df['PredictedSentiment'] = df['compound'].apply(get_sentiment_label)

# Show first 10 rows
df[['Text', 'compound', 'PredictedSentiment']].head(10)

,Text,compound,PredictedSentiment
0,I loved this healthcare AI workshop. The examp...,0.8555,positive
1,"This lecture was okay, but some parts were con...",-0.2263,negative
2,The notebook was easy to follow and very pract...,0.4404,positive
3,I did not like the explanation of the model re...,-0.2755,negative
4,The activity was interesting and helped me und...,0.4019,positive
5,The class was too fast and I could not follow ...,0.0000,neutral
6,"The topic is important, but the instructions w...",0.1027,positive
7,I really enjoyed the examples and the live cod...,0.5563,positive
8,The dataset was messy and the task felt frustr...,-0.6597,negative
9,The exercise was manageable and useful for pra...,0.4404,positive

### Q4. Compare review score and sentiment (2 points)
Group by `Score` and compute the **average compound score** for each score value.

In [6]:
# Write your answer here
# Group by Score and compute average compound
df.groupby('Score')['compound'].mean()

Score
1   -0.507033
2   -0.296125
3   -0.150783
4    0.478340
5    0.621167
Name: compound, dtype: float64

## Part B — Prompt Engineering (10 points)
This part is based on the **Prompt Engineering** notebook. You do **not** need an API key. Focus on writing better prompts using the concepts of **instruction, context, output format, zero-shot, few-shot, and chain-of-thought**.

In [9]:
# Sample texts for the prompt engineering questions
sample_reviews = [
    "The product arrived late and the quality was poor.",
    "Amazing battery life and elegant design.",
    "It is fine for daily use, nothing special."
]
for i, text in enumerate(sample_reviews, start=1):
    print(f"{i}. {text}")

1. The product arrived late and the quality was poor.
2. Amazing battery life and elegant design.
3. It is fine for daily use, nothing special.

### Q1. Zero-shot classification prompt (3 points)
Write a **zero-shot prompt** that asks an AI model to classify each review as **positive, negative, or neutral**.

Your prompt should include:
- a clear instruction
- the three labels
- a request for a clean output format

Store your prompt in a Python variable called `zero_shot_prompt`, then print it.

In [10]:
# Write your answer here
zero_shot_prompt = """
You are a sentiment analysis model.

Classify each of the following reviews into one of these categories:
- positive
- negative
- neutral

Return your answer in the following clean format:
Review 1: <label>
Review 2: <label>
Review 3: <label>

Reviews:
1. The product arrived late and the quality was poor.
2. Amazing battery life and elegant design.
3. It is fine for daily use, nothing special.
"""

print(zero_shot_prompt)

You are a sentiment analysis model.

Classify each of the following reviews into one of these categories:
- positive
- negative
- neutral

Return your answer in the following clean format:
Review 1: <label>
Review 2: <label>
Review 3: <label>

Reviews:
1. The product arrived late and the quality was poor.
2. Amazing battery life and elegant design.
3. It is fine for daily use, nothing special.

### Q2. Few-shot prompt improvement (3 points)
Now improve the previous prompt by adding **two examples**.

Requirements:
- Store it in a variable called `few_shot_prompt`
- Include 2 input-output examples
- Ask the model to classify the 3 sample reviews after the examples

In [11]:
# Write your answer here
few_shot_prompt = """
You are a sentiment analysis model.

Classify each review into:
- positive
- negative
- neutral

Examples:
Review: "I love this product, it works perfectly."
Sentiment: positive

Review: "Terrible experience, I hate it."
Sentiment: negative

Now classify the following reviews:

1. The product arrived late and the quality was poor.
2. Amazing battery life and elegant design.
3. It is fine for daily use, nothing special.

Return output in this format:
Review 1: <label>
Review 2: <label>
Review 3: <label>
"""

print(few_shot_prompt)

You are a sentiment analysis model.

Classify each review into:
- positive
- negative
- neutral

Examples:
Review: "I love this product, it works perfectly."
Sentiment: positive

Review: "Terrible experience, I hate it."
Sentiment: negative

Now classify the following reviews:

1. The product arrived late and the quality was poor.
2. Amazing battery life and elegant design.
3. It is fine for daily use, nothing special.

Return output in this format:
Review 1: <label>
Review 2: <label>
Review 3: <label>

### Q3. Prompt comparison and refinement (4 points)
Create a short table or DataFrame with **three columns**:
- `PromptType`
- `MainFeature`
- `WhyUseful`

Include these three prompt types:
1. Zero-shot
2. Few-shot
3. Chain-of-thought

Then, in **2–3 sentences**, explain which one you would choose for a more difficult text analysis task and why.

In [12]:
# Write your answer here
comparison_df = pd.DataFrame({
    "PromptType": ["Zero-shot", "Few-shot", "Chain-of-thought"],
    "MainFeature": [
        "No examples, only instruction",
        "Includes labeled examples",
        "Includes step-by-step reasoning"
    ],
    "WhyUseful": [
        "Fast and simple for basic tasks",
        "Improves accuracy with examples",
        "Best for complex reasoning tasks"
    ]
})

comparison_df

,PromptType,MainFeature,WhyUseful
0,Zero-shot,"No examples, only instruction",Fast and simple for basic tasks
1,Few-shot,Includes labeled examples,Improves accuracy with examples
2,Chain-of-thought,Includes step-by-step reasoning,Best for complex reasoning tasks

For more difficult text analysis tasks, I would choose Chain-of-thought prompting because it encourages the model to reason step-by-step, leading to more accurate and explainable results. Few-shot is also helpful, but chain-of-thought performs better when the task requires deeper understanding.

## Reflection (optional, no extra points)
Briefly explain the difference between:
- sentiment analysis
- text classification
- prompt engineering

Sentiment Analysis:
Determines emotional tone (positive, negative, neutral) of text.

Text Classification:
Assigns text into predefined categories (e.g., spam, topic, intent).

Prompt Engineering:
Designing effective prompts to guide AI models to produce accurate outputs.